ebury_transform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'ebury_db') }}"
      user: "{{ env_var('POSTGRES_USER', 'ebury_admin') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      schema: public
      threads: 4
